# Generated by Django 6.0 on 2026-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
