# Generated by Django 5.2.8 on 2025-11-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subcategory_icon_name_subcategory_image_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST % (e.g., 5.00, 12.00, 18.00)', max_digits=5),
        ),
    ]
