# Generated by Django 5.2.8 on 2025-11-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(choices=[(0.0, '0% (Exempt)'), (5.0, '5% (Essentials)'), (18.0, '18% (Standard)'), (40.0, '40% (Luxury/Demerit)')], decimal_places=2, default=18.0, help_text='Select applicable GST Slab', max_digits=5),
        ),
    ]
