# Generated by Django 5.2.8 on 2025-11-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Fallback icon name', max_length=50),
        ),
    ]
