# Generated by Django 6.0 on 2026-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_image_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='Harmonized System of Nomenclature code for GST', max_length=20, null=True),
        ),
    ]
