# Generated by Django 6.0 on 2026-01-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_has_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_display_type',
            field=models.CharField(blank=True, default='dropdown', help_text='How to display variants', max_length=50),
        ),
    ]
