# Generated by Django 6.0 on 2026-01-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_variant_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.TextField(blank=True, help_text='Comma separated colors (e.g. Red, Blue, #FF0000)'),
        ),
    ]
