# Generated by Django 6.0 on 2026-05-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_available_colors'),
    ]

    operations = [
        migrations.RunSQL('DROP INDEX IF EXISTS products_brand_is_active_25e413d9;'),
        migrations.RunSQL('DROP INDEX IF EXISTS products_category_is_active_adb3f10a;'),
        migrations.RunSQL('DROP INDEX IF EXISTS products_product_is_active_2e95eb0a;'),
        migrations.RunSQL('DROP INDEX IF EXISTS products_product_stock_status_3536489c;'),
        migrations.RunSQL('DROP INDEX IF EXISTS products_subcategory_is_active_b2fcf626;'),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in-stock', 'In Stock'), ('low-stock', 'Low Stock'), ('out-of-stock', 'Out of Stock')], db_index=True, default='in-stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
