# Generated by Django 5.0.3 on 2026-09-14 23:25

from django.db import migrations, models, connection

def add_image_field_if_not_exists(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='products_producttag' AND column_name='image'"
        )
        if not cursor.fetchone():
            schema_editor.execute(
                "ALTER TABLE products_producttag ADD COLUMN image varchar(100) NULL"
            )

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_producttag_optional_group_subcategories'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_image_field_if_not_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='producttag',
                    name='image',
                    field=models.ImageField(blank=True, help_text='Optional icon/image for the tag', null=True, upload_to='tags/'),
                ),
            ],
        )
    ]
