# Generated by Django 5.0.3 on 2026-09-14 23:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_producttag_optional_group_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional icon/image for the tag', null=True, upload_to='tags/'),
        ),
    ]
